


class Interface(object):
    UI_SIZE_XSMALL = 'UI_SIZE_XSMALL'
    UI_SIZE_SMALL = 'UI_SIZE_SMALL'
    UI_SIZE_MEDIUM = 'UI_SIZE_MEDIUM'
    UI_SIZE_LARGE = 'UI_SIZE_LARGE'
    UI_SIZE_XLARGE = 'UI_SIZE_XLARGE'

    COLOR_TRANSPARENT = (0, 0, 0, 0)
    COLOR_RED = (255, 0, 0)
    COLOR_WHITE = (255, 255, 255)
    COLOR_BLACK = (0, 0, 0)
